// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoT-tMbuGj7Xa7Ol_piWPpBi0N349s73k',
    appId: '1:967549582789:web:93dd8ad80073407c1b9fac',
    messagingSenderId: '967549582789',
    projectId: 'dormdesk-5788b',
    authDomain: 'dormdesk-5788b.firebaseapp.com',
    storageBucket: 'dormdesk-5788b.firebasestorage.app',
    measurementId: 'G-3BFZCQWWB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfsl6GXK-615_e6BKO60Vl49y4XSox9h0',
    appId: '1:967549582789:android:8b7455f968d111a71b9fac',
    messagingSenderId: '967549582789',
    projectId: 'dormdesk-5788b',
    storageBucket: 'dormdesk-5788b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Lu3oS-zgI07BCc6ysbhbsaU3yrYTCdI',
    appId: '1:967549582789:ios:a7434bf44dd06a651b9fac',
    messagingSenderId: '967549582789',
    projectId: 'dormdesk-5788b',
    storageBucket: 'dormdesk-5788b.firebasestorage.app',
    iosBundleId: 'com.example.dormdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Lu3oS-zgI07BCc6ysbhbsaU3yrYTCdI',
    appId: '1:967549582789:ios:a7434bf44dd06a651b9fac',
    messagingSenderId: '967549582789',
    projectId: 'dormdesk-5788b',
    storageBucket: 'dormdesk-5788b.firebasestorage.app',
    iosBundleId: 'com.example.dormdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoT-tMbuGj7Xa7Ol_piWPpBi0N349s73k',
    appId: '1:967549582789:web:6258081a4e38fc061b9fac',
    messagingSenderId: '967549582789',
    projectId: 'dormdesk-5788b',
    authDomain: 'dormdesk-5788b.firebaseapp.com',
    storageBucket: 'dormdesk-5788b.firebasestorage.app',
    measurementId: 'G-413EFR3KGD',
  );

}